### PR TITLE
ci: add GitHub Actions CI config

### PR DESCRIPTION
**Pull request by redeboer**
I doubt how useful cb80c4e is, but this was also in the `.gitlab-ci.yml`. A problem is that installing `texlive` takes quite some time.

### CODE REVIEW

**Comment by redeboer** [comment]
Hmm, not sure why Actions does not start...

**Comment by jiangyi15** [comment]
> I doubt how useful [cb80c4e](https://github.com/jiangyi15/tf-pwa/commit/cb80c4e8a39426d0a82fe7775184e0588919a7a3) is, but this was also in the `.gitlab-ci.yml`. A problem is that installing `texlive` takes quite some time.

It is a weekly work, not every commits.

**Comment by redeboer** [comment]
> It is a weekly work, not every commits.

Ah ok, I can also put `pdflatex` in a separate workflow that only runs on the `master` branch.

**Comment by redeboer** [comment]
> Hmm, not sure why Actions does not start...

When I make a PR to my own fork, the CI does start https://github.com/redeboer/tf-pwa/pull/1

**Pull request merged**
