### PR TITLE
ci: use remote pre-commit only

### PR DESCRIPTION
**Pull request by jiangyi15**

### CODE REVIEW

**Comment by redeboer** [comment]
Small comment: for use in the terminal, this is indeed more convenient, because there's no need anymore to install these formatter and linter packages. In addition, it's easy to upgrade these hooks with `pre-commit autoupdate`, and versions of pre-commit hooks are always pinned to a specific `rev`.

Disadvantage: there is no _single source of truth_ for the version of these packages, in case you want to use packages like `black` through some editor for autoformatting or linting as well (in that case they do need to be installed).

**Comment by jiangyi15** [comment]
@redeboer  So, it is better to add another options for editor user.

**Review by redeboer — APPROVED** [review]
> @redeboer So, it is better to add another options for editor user.

It's all quite tricky, we solved this 'dependency hell' for (developer) packages like this https://github.com/ComPWA/expertsystem/pull/412. But I would worry only about these things if you do run into dependency conflicts or mismatching formatting etc. If not, pre-commit hooks work perfectly fine!

**Comment by jiangyi15** [comment]
@redeboer It looks like complicated. In my side the dependence is limited by less packages (Tensorflow mainly). The conflict is not so tricky.

**Comment by jiangyi15** [comment]
@redeboer It looks like complicated. In my side the dependence is limited by less packages (Tensorflow mainly). The conflict is not so tricky.

**Comment by redeboer** [comment]
Even with one dependency, there are several indirect dependencies, that could cause trouble (that's what's called dependency hell). And that's only the package dependencies. The pre-commit hooks are also requirements that can behave differently depending on their version.

**Comment by jiangyi15** [comment]
That is right, the conflict may exsist. So a virtual environment is recommended.

**Pull request merged**
